# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

frameworkBuild = ENV["FRAMEWORK_BUILD"]

inhibit_all_warnings!

target 'CocoaPodsExample' do
  use_frameworks!

  if frameworkBuild
    pod 'XCF', :path => 'XCF'
  else
    pod 'XCF', :path => 'Temp/Framework'
  end
end

target 'CocoaPodsExampleTests' do
  use_frameworks!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
      if frameworkBuild && 'XCF' == target.name
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
        config.build_settings['SKIP_INSTALL'] = "NO"
      end
    end
  end
end
